#!/bin/bash

APP_FOLDER='navcoin-core'
BDB_PREFIX="/app/${APP_FOLDER}/db4"

mkdir -p $BDB_PREFIX

cd /tmp

# Fetch the source and verify that it is not tampered with
wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
echo '12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef  db-4.8.30.NC.tar.gz' | sha256sum -c

# -> db-4.8.30.NC.tar.gz: OK
tar -xzvf db-4.8.30.NC.tar.gz

# Build the library and install to our prefix
cd db-4.8.30.NC/build_unix/

# Note: Do a static build so that it can be embedded into the executable, instead of having to find a .so at runtime
../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX
make install

cd /app
git clone -b $GIT_REVISION $GIT_REPO $APP_FOLDER

# Install and configure navcoin
./autogen.sh
./configure LDFLAGS="-L${BDB_PREFIX}/lib/" CPPFLAGS="-I${BDB_PREFIX}/include/" --enable-hardening --without-gui --without-miniupnpc
make
make install

# Run daemon
navcoind --daemon
